import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar'
import Section1 from '../components/LandingPage/Section1'
import Section2 from '../components/LandingPage/Section2'
import Section3 from '../components/LandingPage/Section3'
import Section5 from '../components/LandingPage/Section5'
import Footer from '../components/Footer/Footer'
import Section4 from '../components/LandingPage/Section4'

export default function Main() {
  return (
    <>
    <Navbar />
    <div className={styles.container}>
      <Head>
        <title>Hire Job Apps - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section1 />
      <Section2 />
      <Section3 />
      <Section4 />
      <Section5 />

      <Footer />
    </div>
    </>
  )
}
